site_name: anixart
repo_url: https://github.com/SantaSpeen/anixart
site_author: Maxim Khomutov
remote_name: master
use_directory_urls: true

nav:
    - Введение: index.md
    - Общая информация:
        Быстрое начало: home/index.md
        Примеры использования: home/examples.md
    - API библиотеки:
        Введение: api/index.md
        Метки и условные обозночения: api/tags.md
        Методы: api/methods.md
        Неописанные методы: api/todo_methods.md
    - ROADMAP: ROADMAP.md
    - CHANGELOG: CHANGELOG.md
    - Обратная связь: callback.md

theme:
  name: material
  locale: ru
  highlightjs: true
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Включить ночную тему.
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Включить дневную тему.

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
